### ISSUE TITLE
Document package usage better

### ISSUE THREAD

**Issue by jchapuis** [ReactiveX/IxJS#43]
I've had trouble using the package with a webpack-based build, the reason being that the types are not colocated with the .js files. Here's the line in `tsconfig.json` that finally made it work:
```json
"paths" : {
            "ix/*": [ "./node_modules/ix/targets/es5/cjs/*", "./node_modules/ix/types/*" ]
        }
```
How about documenting this better, and even considering shipping with a package that is more "traditional" in structure and works out of the box - similar to the one for rxjs for instance - this would probably ease adoption.

**Comment by trxcllnt** [comment]
If you're working with the default `ix` project, VSCode intellisense works out of the box:
<img width="1666" alt="screen shot 2017-09-12 at 4 16 27 pm" src="https://user-images.githubusercontent.com/178183/30353010-4edaa096-97d8-11e7-84d8-7afe6dcbfb35.png">

The latest versions of webpack should also work without aliasing, since it respects the "module" and "esnext:main" entries in our package.json. Aliasing to `ix/targets/es5/cjs` will make it harder for webpack to tree-shake the dependency tree, defeating the point of importing modules individually.

You should only need a paths entry in tsconfig when using one of the scoped packages (e.g. `@reactivex/ix-es5-cjs`). You're right we should document this, but perhaps its also worth filing an issue with the TypeScript team about types for mapped paths aren't being picked up from the dst module's package.json.

fun fact: I'm also responsible for packaging rxjs, and we're trying to avoid making some of the same mistakes again here. I'm happy to field suggestions on ways to improve the project, work to fix any reported problems, and help shepherd contributions if you have time and the desire to submit PRs, but we ask the tone of all discussions are kept positive. Thanks.

**Comment by jchapuis** [comment]
Thanks for your detailed reply. I'm sorry, maybe I'm missing something trivial - but I still can't figure out how to make it work without the aliasing. I've got the latest vscode, typescript and webpack versions. Attached you'll see my setup. Thanks for any help, and good job on these essential libraries!
![image](https://user-images.githubusercontent.com/7502497/30366813-a322de7c-986c-11e7-9723-bf4af1692a9e.png)

**Comment by trxcllnt** [comment]
@jchapuis we're discussing this in other issues, so I'll be reviewing this weekend when I get a chance. I think adding a `{ paths: "ix/*": ["node_modules/ix/types/*"] }` entry to tsconfig is the quickest fix in the short term. Thanks for filing an issue and for your patience. I'll let you know when I think I have a fix.

**Comment by jchapuis** [comment]
As a side note, I'm also having the same resolution problems with jest now, and will need to find a way to customize the paths for jest too.

**Comment by jchapuis** [comment]
ok I've managed to make jest find Ix by including the following parameter in `package.json`, in the `"jest"` configuration section:

```js
"moduleNameMapper": {
  "ix/(.*)": "<rootDir>/node_modules/ix/targets/es5/cjs/$1"
}
```

**Comment by trxcllnt** [comment]
@jchapuis we just published #45 as `ix@2.1.2` on npm, which should address this issue. Now all the files in the module directly correspond to the path structure in the docs, so you should be able to remove any path mappings you have after you've upgraded. Leave this issue open for a few days so you can still use this thread if there's any trouble. Otherwise, happy hacking!

**Comment by jchapuis** [comment]
@trxcllnt great thanks!

**Comment by LinBoLen** [comment]
angular use package.json to refer different target
```json
{
  "name": "@angular/core",
  "version": "6.0.5",
  "description": "Angular - the core framework",
  "main": "./bundles/core.umd.js",
  "module": "./fesm5/core.js",
  "es2015": "./fesm2015/core.js",
  "esm5": "./esm5/core.js",
  "esm2015": "./esm2015/core.js",
  "fesm5": "./fesm5/core.js",
  "fesm2015": "./fesm2015/core.js",
  "typings": "./core.d.ts",
  "author": "angular",
  "license": "MIT",
  ...
}
```

the reactivex/ixjs have following different target
```
npm install @reactivex/ix-ts # TypeScript target 
npm install @reactivex/ix-es5-cjs # ES5 CommonJS target 
npm install @reactivex/ix-es5-esm # ES5 ESModules target 
npm install @reactivex/ix-es5-umd # ES5 UMD target 
npm install @reactivex/ix-es2015-cjs # ES2015 CommonJS target 
npm install @reactivex/ix-es2015-esm # ES2015 ESModules target 
npm install @reactivex/ix-es2015-umd # ES2015 UMD target 
npm install @reactivex/ix-esnext-esm # ESNext CommonJS target 
npm install @reactivex/ix-esnext-esm # ESNext ESModules target 
npm install @reactivex/ix-esnext-umd # ESNext UMD target
```

I don't know how to unify my import entry?
